model:
  head_cls: ReflectHead
  squeeze_kwargs:
    input_channels: 8
    squeeze_depth: 3
    cam_depth: 1
    conv_starts: 64
    squeeze_start: 16
    ef_start: 64
  head_kwargs:
    in_channels: 64
    mid_channels: 32
    return_value: True
gt_keys:
  - rgb_mask
  - labels
  - intensity_bin
  - intensity_dist
  - mask
loss:
  reflect: True
  l2_weight: 1
  ignore_index: 4
info_fn:
  reflect: True
  ignore_index: 4
base_dir: /mnt/data/vras/Reflectance/model/reflect-best/
pass_keys:
  - depth
  - labels_embed
  - rgb
  - rgb_mask
  - mask
embed:
  num_embeddings: 5
  embedding_dim: 2
  max_norm: 1
embed_channel: labels
store_dir: drgbl