val:
  channels:
    - name: rgb
      start: 8
      end: 11
      scale:
        min: 0
        max: 255.0
      retype: f4
train:
  channels:
    - name: rgb
      start: 8
      end: 11
      scale:
        min: 0
        max: 255.0
      retype: f4
